apiVersion: apps/v1
kind: Deployment
metadata:
  name: datanode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datanode
  template:
    metadata:
      labels:
        app: datanode
    spec:
      containers:
        - name: datanode
          image: hakidon/py-hadoop-datanode
          env:
            - name: SERVICE_PRECONDITION
              value: "namenode-service:9870"
          volumeMounts:
            - name: hadoop-datanode
              mountPath: /hadoop/dfs/data
