apiVersion: apps/v1
kind: Deployment
metadata:
  name: historyserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: historyserver
  template:
    metadata:
      labels:
        app: historyserver
    spec:
      containers:
        - name: historyserver
          image: hakidon/py-hadoop-historynode
          env:
            - name: SERVICE_PRECONDITION
              value: "namenode-service:9000 namenode-service:9870 datanode-service:9864 resourcemanager-service:8088"
          volumeMounts:
            - name: hadoop-historyserver
              mountPath: /hadoop/yarn/timeline
---
apiVersion: v1
kind: Service
metadata:
  name: historyserver-service
spec:
  selector:
    app: historyserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80