apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodemanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodemanager
  template:
    metadata:
      labels:
        app: nodemanager
    spec:
      containers:
        - name: nodemanager
          image: hakidon/py-hadoop-managernode
          env:
            - name: SERVICE_PRECONDITION
              value: "namenode-service:9000 namenode-service:9870 datanode-service:9864 resourcemanager-service:8088"
